---
- name: "COMMON | Update apt cache and upgrade packages"
  ansible.builtin.apt:
    upgrade: full
    update_cache: yes
    cache_valid_time: 3600

- name: "COMMON | Install common packages"
  ansible.builtin.apt:
    name:
      - cron
      - tmux
      - htop
      - sudo
      - curl
      - cifs-utils
      - nfs-common
      - net-tools
      - tree
      - gnupg2
    state: present