---
- name: "Provision & Configure Server: {{ target_server }}"
  hosts: all
  gather_facts: false
  vars:
    public_repo_path: "{{ playbook_dir | dirname }}/roles/homelab_data"
    private_repo_path: "{{ inventory_dir }}"

  tasks:
    - name: "STEP 1: Load PUBLIC server definition"
      ansible.builtin.include_vars:
        file: "{{ public_repo_path }}/{{ target_server }}/config/main.yaml"
        name: server_config
      delegate_to: localhost
      run_once: true

    - name: "STEP 2: Find and prepare LXC template on Proxmox"
      block:
        - name: "Find latest template version"
          ansible.builtin.command: "pveam available --output-format json"
          register: pve_available_templates
          changed_when: false
        - name: "Set latest template path fact"
          ansible.builtin.set_fact:
            latest_template_path: "{{ (pve_available_templates.stdout | from_json | selectattr('template', 'match', server_config.proxmox.template_short_name) | list | first).template }}"
        - name: "Download template if needed"
          ansible.builtin.command: "pveam download {{ proxmox_template_storage }} {{ latest_template_path }}"
      delegate_to: "{{ proxmox_host }}"
      run_once: true

    - name: "STEP 3: Create LXC container"
      community.proxmox.proxmox:
        api_user: "{{ proxmox_api_user }}"
        api_token_id: "{{ proxmox_api_token_id }}"
        api_token_secret: "{{ proxmox_api_token_secret }}"
        api_host: "{{ proxmox_host }}"
        node: "{{ server_config.proxmox.node }}"
        vmid: "{{ server_config.proxmox.vmid }}"
        hostname: "{{ server_config.proxmox.hostname }}"
        password: "{{ proxmox_root_password }}"
        ostemplate: "{{ proxmox_template_storage }}:vztmpl/{{ latest_template_path }}"
        netif: "{{ server_config.proxmox.netif }}"
        rootfs: "{{ server_config.proxmox.rootfs }}"
        state: present
      register: proxmox_lxc
      delegate_to: localhost
      run_once: true

    - name: "Add new server to in-memory inventory"
      ansible.builtin.add_host:
        name: "{{ target_server }}"
        ansible_host: "{{ proxmox_lxc.ip_addresses.eth0.ipv4 }}"
      when: proxmox_lxc.changed
      delegate_to: localhost
      run_once: true

    - name: "Wait for SSH on the new server"
      ansible.builtin.wait_for_connection:
        delay: 5
        timeout: 300
      delegate_to: "{{ target_server }}"
      run_once: true

    - name: "STEP 4: Apply roles on target server"
      block:
        - name: Apply baseline common role
          ansible.builtin.import_role:
            name: common

        - name: Apply software roles
          ansible.builtin.include_role:
            name: "{{ item }}"
          loop: "{{ server_config.roles | default([]) }}"
      delegate_to: "{{ target_server }}"
      run_once: true

    - name: "STEP 5: Sync public file structure to server"
      ansible.posix.synchronize:
        src: "{{ public_repo_path }}/{{ target_server }}/files/"
        dest: "/"
        rsync_opts: ["--archive", "--delete", "--verbose"]
      delegate_to: "{{ target_server }}"
      run_once: true

    - name: "STEP 6: Sync private file structure to server"
      ansible.posix.synchronize:
        src: "{{ private_repo_path }}/{{ target_server }}/files/"
        dest: "/"
        rsync_opts: ["--archive", "--verbose"]
      delegate_to: "{{ target_server }}"
      run_once: true