---
# Run with: ansible-playbook playbooks/update_all.yaml
- name: "Update All Servers"
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    public_repo_path: "../homelab"
    private_repo_path: "../homelab-private"

  pre_tasks:
    - name: Load server definitions
      ansible.builtin.include_vars:
        file: "{{ public_repo_path }}/{{ inventory_hostname }}/config/main.yaml"
        name: server_config

  roles:
    - role: common
    - role: "{{ item }}"
      loop: "{{ server_config.roles | default([]) }}"

  tasks:
    - name: "Sync public file structure"
      ansible.posix.synchronize:
        src: "{{ public_repo_path }}/{{ inventory_hostname }}/files/"
        dest: "/"
        rsync_opts: ["--archive", "--delete"]
      delegate_to: "{{ inventory_hostname }}"

    - name: "Sync private file structure"
      ansible.posix.synchronize:
        src: "{{ private_repo_path }}/{{ inventory_hostname }}/files/"
        dest: "/"
        rsync_opts: ["--archive"]
      delegate_to: "{{ inventory_hostname }}"